version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: Admin007
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  pgdata:
